name: technical_indicators
description: null
version: 0.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies: null
dev_dependencies:
  dartz: ^0.10.1
  kite_connect:
    path: ../kite_connect
  test: ^1.19.5
